/**
 * POST /api/v1/analyze  (redirected to this function — see netlify.toml)
 * Body: { brand: string }
 * Header: Authorization: Bearer bb_live_...
 *
 * The real public API endpoint documented in ApiDocs.tsx and generated by
 * Developers.tsx > API Keys. Authenticated with a Presora API key, not a
 * user session — see _lib/apiKeyAuth.js. Runs the same scan core as the
 * in-app scan (analyze.js) and persists the result the same way, so a key
 * holder's programmatic scans show up in their Reports the same as manual
 * ones.
 */
import { createClient } from '@supabase/supabase-js';
import ws from 'ws';
import { OPENROUTER_MODELS, runBrandScan, summariseFailures } from './_lib/runScan.js';
import { verifyApiKey, checkRateLimitAndLog } from './_lib/apiKeyAuth.js';
import { fireWebhooksForEvent } from './_lib/webhookDelivery.js';
import { getScanSettings } from './_lib/appSettings.js';

if (!globalThis.WebSocket) globalThis.WebSocket = ws;

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY;

const PLAN_TIER = { free: 0, starter: 1, solo: 1, growth: 2, enterprise: 2, agency: 2 };

export const handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Method not allowed' }) };
  }
  if (event.body && event.body.length > 4 * 1024) {
    return { statusCode: 413, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Payload too large' }) };
  }

  let supabaseAdmin;
  try {
    supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
      auth: { autoRefreshToken: false, persistSession: false },
    });
  } catch (err) {
    console.error('api-analyze: Supabase client init failed:', err.message);
    return { statusCode: 500, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Server misconfiguration' }) };
  }

  const auth = await verifyApiKey(supabaseAdmin, event.headers.authorization || event.headers.Authorization);
  if (!auth) {
    return { statusCode: 401, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Invalid or revoked API key' }) };
  }

  // Persistent, DB-backed — see checkRateLimitAndLog's comment for why an
  // in-memory counter doesn't actually bound anything on Netlify Functions.
  const allowed = await checkRateLimitAndLog(supabaseAdmin, auth.keyId, auth.userId, { windowMs: 60_000, max: 10, kind: 'analyze' });
  if (!allowed) {
    return { statusCode: 429, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Rate limit exceeded' }) };
  }

  let brandName;
  try {
    const body = JSON.parse(event.body || '{}');
    brandName = String(body.brand || '').trim().slice(0, 500);
  } catch {
    return { statusCode: 400, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Invalid JSON' }) };
  }
  if (!brandName) {
    return { statusCode: 400, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: '"brand" is required' }) };
  }

  try {
    // Same admin kill-switch analyze.js honours — don't charge an API
    // call against a scan that can't run.
    const scanSettings = await getScanSettings(supabaseAdmin);
    if (!scanSettings.enabled) {
      return { statusCode: 503, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Scanning is temporarily paused. Please try again later.' }) };
    }

    const { data: profile } = await supabaseAdmin.from('profiles').select('plan').eq('id', auth.userId).single();
    const planTier = PLAN_TIER[String(profile?.plan || 'free').toLowerCase()] ?? 0;
    const models = OPENROUTER_MODELS.filter((m) => m.tier <= planTier);

    const result = await runBrandScan({ supabaseAdmin, target: brandName, models, userId: auth.userId, openrouterEnabled: scanSettings.openrouterEnabled });

    // A fallback result is fabricated (deterministic, not from any real
    // model) — never save/return that as a genuine analysis via the public
    // API. Throw into the catch block below so it's a 500, not a paid API
    // call silently billed against fake data.
    if (result.isFallback) {
      // Mirrors analyze.js: name the actual cause instead of collapsing a
      // missing key, an empty balance and a retired model id into one string.
      throw new Error(
        result.keyConfigured === false
          ? 'OPENROUTER_API_KEY is not configured on this deploy'
          : result.failures?.length
            ? `All ${result.failures.length} model call(s) rejected — ${summariseFailures(result.failures)}`
            : 'All model providers failed (no error detail returned)'
      );
    }

    const { data: saved, error: insertError } = await supabaseAdmin
      .from('analyses')
      .insert({
        user_id: auth.userId,
        brand_name: brandName,
        trust_score: result.trustScore,
        authority: result.authority,
        sentiment: result.sentiment,
        recency: result.recency,
        mentions: result.mentions,
        accuracy: result.accuracy,
        sources: result.sources,
      })
      .select('id, created_at')
      .single();
    if (insertError) console.error('api-analyze: failed to save analysis:', insertError.message);

    const responseBody = { id: saved?.id ?? null, brandName, createdAt: saved?.created_at ?? new Date().toISOString(), ...result };

    fireWebhooksForEvent(supabaseAdmin, { userId: auth.userId, event: 'analysis.completed', payload: responseBody })
      .catch((err) => console.error('api-analyze: webhook firing failed:', err.message));

    return { statusCode: 200, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(responseBody) };
  } catch (err) {
    console.error('api-analyze handler error:', err.message);
    fireWebhooksForEvent(supabaseAdmin, { userId: auth.userId, event: 'analysis.failed', payload: { brandName, error: err.message } })
      .catch(() => {});
    return { statusCode: 500, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Analysis failed. Please try again.' }) };
  }
};
